### ISSUE TITLE
 installation error of wxparaver

### ISSUE THREAD

**Issue by sheldon-pan** [bsc-performance-tools/wxparaver#2]
Hello,I am a student and a user of an HPC cluster. I am trying to install Extrae and Wxparaver.
When I installed wxparaver, I was prompted not to link to boost serialization, but I have set the path.
This is after 
./configure --with-boost=/home/xd/boost --with-boost_serialization=/home/xd/boost
./make

 /bin/sh ./libtool --tag=CXX --mode=link g++ -I../include/ -I../api/ -I../ -I../../ -g -O2 - I/home/xd/boost/include -I/usr/local/include/libxml2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -O2 -g -L/home/xd/boost/lib -lboost_date_time -R /home/xd/ Boost/lib -L/usr/local/lib -lxml2 -lm -ldl -o paramedir.bin api/paramedir.o -lz api/libparaver-api.la src/libparaver-kernel.la
Libtool: link: g++ -I../include/ -I../api/ -I../ -I../../ -g -O2 -I/home/xd/boost/include -I/usr /local/include/libxml2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -O2 -g -o .libs/paramedir.bin api/paramedir.o -L/home/xd/boost/lib -L/usr/local/lib - Lz api/.libs/libparaver-api.so src/.libs/libparaver-kernel.so -lboost_serialization -lboost_date_time /usr/local/lib/libxml2.so -lm -ldl -Wl,-rpath -Wl,/usr/ Local/lib/paraver-kernel -Wl,-rpath -Wl,/home/xd/boost/lib
`
_`Api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_iarchive<boost::archive::xml_iarchive>::load_override(boost::archive::object_id_type&, int)'`_
Api/.libs/libparaver-api.so: undefined reference to `boost::archive::detail::shared_ptr_helper::shared_ptr_helper()'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_oarchive<boost::archive::xml_oarchive>::save_override(boost::archive::class_id_reference_type const&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::detail::shared_ptr_helper::~shared_ptr_helper()'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_oarchive<boost::archive::xml_oarchive>::save_override(boost::archive::object_reference_type const&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_oarchive<boost::archive::xml_oarchive>::save_override(boost::archive::class_id_type const&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::xml_iarchive_impl<boost::archive::xml_iarchive>::load_override(boost::archive::class_name_type&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_oarchive<boost::archive::xml_oarchive>::save_override(boost::archive::tracking_type const&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_iarchive<boost::archive::xml_iarchive>::load_override(boost::archive::class_id_type&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_oarchive<boost::archive::xml_oarchive>::save_override(boost::archive::class_name_type const&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_oarchive<boost::archive::xml_oarchive>::save_override(boost::archive::object_id_type const&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_oarchive<boost::archive::xml_oarchive>::save_override(boost::archive::version_type const&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_oarchive<boost::archive::xml_oarchive>::save_override(boost::archive::class_id_optional_type const&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_iarchive<boost::archive::xml_iarchive>::load_override(boost::archive::version_type&, int)'
api/.libs/libparaver-api.so: undefined reference to `boost::archive::basic_xml_iarchive<boost::archive::xml_iarchive>::load_override(boost::archive::tracking_type&, int)'
collect2: error: ld returned 1 exit status
make[5]: *** [paramedir.bin] Error 1
make[5]: Leaving directory `/root/lib/wxparaver-4.8.1/src/paraver-kernel'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/root/lib/wxparaver-4.8.1/src/paraver-kernel'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/root/lib/wxparaver-4.8.1/src/paraver-kernel'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/lib/wxparaver-4.8.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/lib/wxparaver-4.8.1'
make: *** [all] Error 2`

**Comment by executre** [comment]
Please, try setting the boost libraries directory using the configure flag: --with-boost-libdir

**Comment by exaexa** [comment]
+1, I have the same problem on debian systems (tried both stable and testing). What's the expected value for the boost libdir on debians?

**Comment by exaexa** [comment]
OK it was probably a wrong setting of a default path. `--with-boost-libdir=/usr/lib/x86_64-linux-gnu/` seems to work.
