### ISSUE TITLE
Paraver doesn't show the value 51

### ISSUE THREAD

**Issue by rodarima** [bsc-performance-tools/wxparaver#5]
Hi, I have a problem when loading a trace. The value 51 is not shown and the cursor doesn't show anything when I click over the "missing" region. Here is a reproducer trace and config [thread.tar.gz](https://github.com/bsc-performance-tools/wxparaver/files/7691525/thread.tar.gz). This is what the PRV trace looks like:
```
#Paraver (19/01/38 at 03:14):20_ns:0:1:1(1:1)
2:0:1:1:1:0:23:7
2:0:1:1:1:10:23:51
2:0:1:1:1:11:23:7
2:0:1:1:1:20:23:0
```
Which contains only events, starting at value 7, then 51, then 7 and then 0 at the end. However this is what I see on the last release of [paraver 4.9.2 on Linux](https://ftp.tools.bsc.es/wxparaver/wxparaver-4.9.2-Linux_x86_64.tar.bz2):

![error-51](https://user-images.githubusercontent.com/3866127/145549727-232f3320-8c36-4a80-b1bd-561eb5671961.png)

To reproduce, run `wxparaver thread.prv thread.cfg`.

**Comment by executre** [comment]
Fixed in paraver-kernel library: [https://github.com/bsc-performance-tools/paraver-kernel/commit/faeda14fc3cbd09ba8c37c45ecfa8c97d482210b](url)

**Comment by rodarima** [comment]
Thanks Eloy, I tested it with the last release 4.10.0 and it works fine.
