### ISSUE TITLE
Missing labels in the Color dialog

### ISSUE THREAD

**Issue by rodarima** [bsc-performance-tools/wxparaver#7]
I come accross a trace that causes wxparaver 4.10.4 to ignore the labels of the states on the timeline, in the "Colors" dialog.

If I move the mouse on top, the label is displayed properly in the bottom axis of the timeline, but they don't appear in the Colors list. If I export the legend, they are ok too.

![missing-label](https://user-images.githubusercontent.com/3866127/191772613-b848286a-4c8f-41e9-9b32-63b66d5aced8.png)

The PCF contains the values for the states, which are quite large:

```
EVENT_TYPE
0 36         Label
VALUES
777  Option1
41128910  Option2
263854781  Option3
749550192  Option4
1091980496  Option5
1423278271  Option6
1719266019  Option7
```

I attach the reproducer [missing-labels.zip](https://github.com/bsc-performance-tools/wxparaver/files/9626667/missing-labels.zip).

**Comment by executre** [comment]
Solved in commit [49a05e9](https://github.com/bsc-performance-tools/wxparaver/commit/49a05e9ebcdaf03cac3efb67be1a7cb1150c3c42)

**Comment by rodarima** [comment]
Thanks, could it be possible to have a patch release that includes this 
commit?

**Comment by executre** [comment]
You can download a development package with this issue solved from here:
[https://ftp.tools.bsc.es/wxparaver/4.10.4-devel/wxparaver-4.10.4-devel-Linux_x86_64.tar.bz2](https://ftp.tools.bsc.es/wxparaver/4.10.4-devel/wxparaver-4.10.4-devel-Linux_x86_64.tar.bz2)

or if you want the source code:
[https://ftp.tools.bsc.es/wxparaver/4.10.4-devel/wxparaver-4.10.4-devel-src.tar.bz2](https://ftp.tools.bsc.es/wxparaver/4.10.4-devel/wxparaver-4.10.4-devel-src.tar.bz2)
